# -*- coding: utf-8 -*-
"""「GenZ_LineBot_Gemini+Multi+Template」的副本(for vercel)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ige0l_aadVTksBREhvOptpy0cZ6ytEF
"""

import os
from flask import Flask, request, abort

from linebot.v3 import WebhookHandler
from linebot.v3.exceptions import InvalidSignatureError
from linebot.v3.webhooks import MessageEvent, TextMessageContent
from linebot.v3.messaging import (
    Configuration, ApiClient, MessagingApi,
    ReplyMessageRequest,
    TextMessage,
    StickerMessage,
    ImageMessage,
    VideoMessage,
    LocationMessage,
    TemplateMessage,
    ConfirmTemplate, MessageAction,
    ButtonsTemplate, URIAction, LocationAction, CameraAction, CameraRollAction,
    CarouselTemplate, CarouselColumn, URIAction, PostbackAction
)

app = Flask(__name__)

configuration = Configuration(access_token=os.getenv('Line_Access_Token'))
line_handler = WebhookHandler(os.getenv('Line_Channel_Secret'))

@app.route("/callback", methods=['POST'])
def callback():
    signature = request.headers['X-Line-Signature']
    body = request.get_data(as_text=True)
    try:
        line_handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)
    return 'OK'

import google.generativeai as genai

genai.configure(api_key=os.getenv('GOOGLE_API_KEY'))
model = genai.GenerativeModel('gemini-2.0-flash')
def ask_gemini(question):
      prompt = (
        "You are a Gen Z kid. Answer the following question in a casual, funny, and relatable Gen Z style. "
        "Use internet slang, abbreviations, emojis, and vibe-y energy when appropriate. Be cool but informative. "
        f"Here’s the question: {question}"
    )
      response = model.generate_content(prompt)
      return response.text

@line_handler.add(MessageEvent, message=TextMessageContent)
def handle_message(event):
    with ApiClient(configuration) as api_client:
        line_bot_api = MessagingApi(api_client)

        action = event.message.text
        if action.lower() == 'sticker':
          reply = StickerMessage(package_id='6136', sticker_id='10551379') #回覆貼圖 (https://developers.line.biz/en/docs/messaging-api/sticker-list/#sticker-definitions)
        elif action.lower() == 'I love u gang':
          reply = ImageMessage(original_content_url='https://www.diploma-degree.com/Degree/700-337000-Brainrot-certificate.jpg', preview_image_url='https://www.diploma-degree.com/Degree/700-337000-Brainrot-certificate.jpg') #回覆圖片
        elif action.lower() == 'recommend some good movies gang':
          reply = VideoMessage(original_content_url='https://media-hosting.imagekit.io/98ad6eca4fa743c5/768813243.887167.mp4?Expires=1841728988&Key-Pair-Id=K2ZIVPTIP2VGHC&Signature=1fEr0cQ1RX03SWoZsFvcx7o9fWoMPp~Cz9PGMWMg2a4H-pPnFriq0~W~A-QURLiQUhF3P0OhNWeo-q6pbM5NJKfobiBsAziHNr2bTsrs80mqghh66xU8OHJ47IvAZfGH6gc77s8QUgbXSiBsneNN1qyjcBa1dB1IK0CUzGP9z81gg223nzE8XsJHnivOXfMJAdjEMzEO2R~UVp9FoFNwymYvfesnwMpLgIOW3FKtniXzrGiu0rOGfuNol1ZJvvAOCt1IDeirommHJj5atUNLgzrpvq-vfbCs6aZNiDYzTVwmdNE5pC1wAO1HH9FrZe7r8fgnc9RCGxBX~IBdRRbI2g__', preview_image_url='https://www.clipartmax.com/png/middle/102-1025923_shhh-shh-emoji.png')
        elif action.lower() == 'where do you live':
          reply = LocationMessage(title="王家檳榔",address="801高雄市前金區",latitude=22.628453980697824,longitude=120.29870725724652)
        elif action.lower() == 'missions':
           button_template = ButtonsTemplate(
            thumbnail_image_url='https://sdmntprsouthcentralus.oaiusercontent.com/files/00000000-c724-61f7-bfc3-c6bc9cbada57/raw?se=2025-05-13T09%3A11%3A12Z&sp=r&sv=2024-08-04&sr=b&scid=00000000-0000-0000-0000-000000000000&skoid=24a7dec3-38fc-4904-b888-8abe0855c442&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-05-12T22%3A06%3A22Z&ske=2025-05-13T22%3A06%3A22Z&sks=b&skv=2024-08-04&sig=NZ3W3Eoe5kWixRilvkG4OfYo7GEw7XWdbJQMYpuk3nQ%3D',
            title="Missions",
            text="assigned by Andy",
            actions=[
                URIAction(label="代辦清單", uri="https://www.instagram.com/andrew_c_0402/"),
                URIAction(label="目標位置", uri="https://maps.app.goo.gl/HGoeZMJmCd5gfkS98"),
            ]
           )
           reply = TemplateMessage(
              alt_text = 'Missions',
              template = button_template)
        else:
          response = ask_gemini(action) #gemini回覆
          reply = TextMessage(text=response)


        response = ask_gemini(event.message.text)
        line_bot_api.reply_message(
            ReplyMessageRequest(
                reply_token=event.reply_token,
                messages=[
                    reply
                ]
            )
        )



if __name__ == "__main__":
    app.run()

